- name: "create directory"
  file:
    state: directory
    owner: root
    group: root
    mode: 0755
    path: "{{ item }}"
  with_items:
    - "{{ doris_manager__dir_home }}"
    - "{{ doris_manager__dir_upload }}"

- name: "upload and uncompress doris_manager install media"
  unarchive:
    owner: root
    group: root
    mode: 0755
    src: "{{ doris_manager__install_media }}"
    dest: "{{ doris_manager__dir_upload }}"

- name: "copy doris_manager to doris_manager home directory"
  shell: |
    cp -rf {{ doris_manager__install_media_uploaded }}/* {{ doris_manager__dir_home }}

# - name: "upload doris_manager install media"
#   copy:
#     force: yes
#     owner: root
#     group: root
#     mode: 0755
#     remote_src: no
#     src: "{{ doris_manager__install_media }}"
#     dest: "{{ doris_manager__install_media_uploaded }}"

# - name: "uncompress doris_manager install media"
#   shell: |
#     tar -xzf {{ doris_manager__install_media_uploaded }} -C {{ doris_manager__dir_home }}

- name: "doris_manager webserver / config file / manager.conf"
  template:
    owner: root
    group: root
    mode: 0755
    src: "webserver_manager.conf.j2"
    dest: "{{ doris_manager__dir_home }}/webserver/conf/manager.conf"
